# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:54
from __future__ import unicode_literals

from django.db import migrations

from myadmin.models import AdminPanel


def create_adminpanel_forwards_func(apps, schema_editor):
    """
    Create object for AdminPanel.
    """
    AdminPanel.objects.create()


def create_adminpanel_backwards_func(apps, schema_editor):
    """
    Delete all objects of AdminPanel
    """
    AdminPanel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=create_adminpanel_forwards_func,
            reverse_code=create_adminpanel_backwards_func,
        ),
    ]
