# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_create_adminpanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpanel',
            name='models_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
