# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20170824_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpanel',
            options={'permissions': (('access_panel', 'Can access myadmin panel'),)},
        ),
    ]
